services:
  banco:
    image: postgres:16
    container_name: shopflow-banco
    environment:
      POSTGRES_USER: shopflow
      POSTGRES_PASSWORD: shopflow123
      POSTGRES_DB: shopflow
    ports:
      - "5433:5432"
    volumes:
      - dados_banco:/var/lib/postgresql/data

volumes:
  dados_banco:
